Page({
    data:{
        jc_classify_cont:[
            {
                title:"做一只好奇的猫",
                remark:"科普",
                label:["仿学生","皱纹","超新星"]
            },
             {
                title:"菇凉小伙有格调",
                remark:"人文",
                label:["十二生肖","饮食禁忌","南京大屠杀"]
            },
             {
                title:"ACGN，你好",
                remark:"二次元",
                label:["熊本熊","穿越","头文字D"]
            },
             {
                title:"谁没点黑历史",
                remark:"人物",
                label:["迪福","董明珠","唐纳德·特朗普"]
            },
             {
                title:"人家不只有A面",
                remark:"性情",
                label:["自负","变态","起床气"]
            },
             {
                title:"世界变化太快",
                remark:"新鲜事儿",
                label:["速度与激情","《天龙八部》","国界"]
            },
             {
                title:"我读书少别骗我",
                remark:"新解词语",
                label:["套路","粉丝","网络暴力"]
            },
             {
                title:"人人都有病",
                remark:"常见病",
                label:["冻伤","白血病","咳嗽"]
            },
             {
                title:"逗逼美丑不挑剔",
                remark:"晒图",
                label:["钢笔","有颜任性","丑"]
            },
             {
                title:"随手甩出正能量",
                remark:"正能量",
                label:["无国界医生","心态","国歌"]
            },
             {
                title:"掰着手指慢慢数",
                remark:"数学",
                label:["线性规划","十进制","贾宪三角"]
            },
             {
                title:"人生赢家第一步",
                remark:"经济学",
                label:["SDR","体验消费","TPP"]
            },
             {
                title:"叽里咕噜说啥呢",
                remark:"外文",
                label:["韩语","世界语","英语"]
            }

        ],
        jc_user:[
            {
                src:"/images/ic_look_at_picture.png",
                name:"K先生",
                friends:37
            },
            {
                src:"/images/ic_look_at_picture.png",
                name:"K先生",
                friends:37
            },
            {
                src:"/images/ic_look_at_picture.png",
                name:"K先生",
                friends:37
            },
             {
                src:"/images/ic_look_at_picture.png",
                name:"K先生",
                friends:37
            },
             {
                src:"/images/ic_look_at_picture.png",
                name:"K先生",
                friends:37
            },
             {
                src:"/images/ic_look_at_picture.png",
                name:"K先生",
                friends:37
            },
             {
                src:"/images/ic_look_at_picture.png",
                name:"K先生",
                friends:37
            },
        ]
    }

})